spring:
  datasource:
    url: jdbc:mysql://localhost:3306/4juniors?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect