spring:
  datasource:
    url: jdbc:mysql://localhost:3306/4juniors?useSSL=false&serverTimezone=UTC
    username: root
    password: admin
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true