server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DATABASE:4juniors}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

#amazon S3
cloud:
  aws:
    region:
      static: ${S3_SERVER_REGION}
    stack:
      auto: false
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
logging:
  level:
    org.hibernate.SQL: debug
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error

# security
jwt:
  secret: ${SECRET_KEY}
  expiration: ${KEY_EXPIRATION_TIME}
